web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./web-static.ldjam.com:/code
        - ./files/static.conf:/etc/nginx/conf.d/static.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./web-static.ldjam.com:/code
